spring.application.name=RA_Billing

# Database connection URL, username, and password
spring.datasource.url=jdbc:mysql://localhost:3306/ra_billing?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
